name: push

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get version
        run: echo "VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Get short version
        run: echo "SHORT_VERSION=${VERSION%.*}" >> $GITHUB_ENV

      - name: Build docker image
        run: docker build -t yakim/tg_upload_proxy:latest -t yakim/tg_upload_proxy:${VERSION} -t yakim/tg_upload_proxy:${SHORT_VERSION} .
      - name: Smoke test
        run: "docker run --rm yakim/tg_upload_proxy --help | grep 'usage: tg_upload_proxy_api '"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: yakim
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push images
        run: docker push yakim/tg_upload_proxy --all-tags
