name: build

on: [push, pull_request]

jobs:
  checks:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install flake8
        run: |
          pip install flake8

      - name: Linting
        run: |
          make lint

  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        uses: docker://python:3.8
        with:
          args: /bin/bash -c "pip install -Ue '.[dev]' && pytest --cov --cov-report=xml --cov-report=term"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
